Move feature into a src directory
If I set  base-path-to-features to ".", the workflow passes validation
for "tailscale/devcontainer-feature.json" but fails because it expects
a devcontainer-feature.json in every possible path:
```
Error: (!) ERR: devcontainer-feature.json not found at path 'LICENSE/devcontainer-feature.json'.
Error: (!) ERR: devcontainer-feature.json not found at path 'README.md/devcontainer-feature.json'.
Error: (!) ERR: devcontainer-feature.json not found at path 'codespace.jpg/devcontainer-feature.json'.
```

If I do not set base-path-to-features, the workflow fails because scandir fails:
```
Validating Feature metadata...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, scandir ''] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: ''
}
```

I note that all existing devcontainer features I can find follow the example of
https://github.com/devcontainers/feature-starter and put their code into a src
directory, and maybe that is the only way the publish workflow was tested. Try that.

Signed-off-by: Denton Gentry <dgentry@tailscale.com>